### PR TITLE
Update to 1.9.6

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by sannykr** [comment]
@conda-forge/django-extensions : Could you please review and merge.

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender.

**Comment by pkgw** [comment]
@sannykr Merge approval for individual feedstocks would be from @conda-forge/django-extensions , not staged-recipes.

**Comment by jakirkham** [comment]
...or another team name derived from the feedstock (for different feedstocks).

**Comment by sannykr** [comment]
Thanks. I just changed the comment.

**Comment by kwilcox** [comment]
Would have preferred a clean commit history but I'm feeling rather nice today :smiley: :smiley:

**Pull request merged**
